### PR TITLE
Correct varnish `thread` state description

### PR DESCRIPTION
**Pull request by dbenamydd**
Based on https://www.varnish-cache.org/docs/4.1/reference/varnish-counters.html

### CODE REVIEW

**Comment by dbenamydd** [comment]
@kky I guess?

**Comment by JayJayM** [comment]
Thanks @dbenamydd !
Does it change the meaning of the description? 
Is "being used" not accurate?

**Comment by vagelim** [comment]
If we're going to change it, I'd say go with something like: 
> Number of threads in all pools.
or
> Total number of threads
from the link @dbenamydd  referenced.

Either of those is better than the somewhat ambiguous "number of threads" (just _number of threads_ leaves me wondering, does it represent the current number, total number, or is it an incrementing counter of all threads created, etc)

**Comment by JayJayM** [comment]
I agree with @vagelim .  
Does "Number of threads in all pools" works for everyone? 
@dbenamydd ?

**Comment by dbenamydd** [comment]
> Does it change the meaning of the description? 
> Is "being used" not accurate?

Assuming that other page means what it sounds like, I assume the metric includes idle threads, while "being used" might exclude them.

> If we're going to change it, I'd say go with something like:
> 
> Number of threads in all pools
> Total number of threads

> Either of those is better than the somewhat ambiguous "number of threads" (just number of threads leaves me wondering, does it represent the current number, total number, or is it an incrementing counter of all threads created, etc)

I didn't include "total" in the PR because it feels a bit weird to me, like asking "how many total ppl work at datadog?" rather than the more natural "how many ppl work at datadog?". I also though that total might add ambiguity about it being the cumulative number of threads created.

I can't think of a perfect solution though and don't have strong feelings so I'm happy to change it.

**Comment by dbenamydd** [comment]
@JayJayM I don't have write access to this repo. Can I trouble you to add me and/or merge this?

**Pull request merged**
